const js = require('@eslint/js');

module.exports = [
  {
    ignores: ['vue-model-manager/**/*'],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2025,
      sourceType: 'commonjs',
      globals: {
        console: 'readonly',
        process: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        AbortSignal: 'readonly',
        AbortController: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        structuredClone: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        document: 'readonly',
        window: 'readonly',
        Node: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { args: 'none' }],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];