// Map external community-source provider names to datapoint_providers.slug
const PROVIDER_MAP = {
  'google ai studio': 'google',
  'nvidia nim': 'nvidia',
  'opencode zen': 'opencode',
  'mistral (la plateforme)': 'mistral',
  'mistral (codestral)': 'mistral',
  'github models': 'github-models',
  'cloudflare workers ai': 'cloudflare',
  'together': 'together',
  'fireworks': 'fireworks',
  'vercel ai gateway': 'vercel',

  // ── Mastra provider name → datapoint_providers.slug ──────────
  // Exact slug matches between Mastra .mdx filenames and our provider slugs
  'anthropic': 'anthropic',
  'cerebras': 'cerebras',
  'cohere': 'cohere',
  'deepinfra': 'deepinfra',
  'deepseek': 'deepseek',
  'github-models': 'github-models',
  'google': 'google',
  'groq': 'groq',
  'llmgateway': 'llmgateway',
  'mistral': 'mistral',
  'nvidia': 'nvidia',
  'openai': 'openai',
  'opencode': 'opencode',
  'openrouter': 'openrouter',
  'siliconflow': 'siliconflow',
  'vercel': 'vercel',

  // Mastra names that need explicit remapping to our slug
  'cloudflare-ai-gateway': 'cloudflare',
  'cloudflare-workers-ai': 'cloudflare',
  'fireworks-ai': 'fireworks',
  'novita-ai': 'novitaai',
  'siliconflow-cn': 'siliconflow',
  'togetherai': 'together',

  // Mastra providers not yet in our datapoint_providers (map to null for future)
  'perplexity': null,
  'perplexity-agent': null,
  'xai': 'xai',
  'zhipuai': 'zhipuai',
  'zhipuai-coding-plan': 'zhipuai',

  // ── models.dev provider name → datapoint_providers.slug ──────────
  'x-ai': 'xai',
  'mistralai': 'mistral',
  'z-ai': 'zhipuai',
  'moonshotai': 'openrouter',
  'qwen': 'openrouter',
  'meta-llama': 'openrouter',
  'bytedance': 'openrouter',
  'bytedance-seed': 'openrouter',
  'minimax': 'openrouter',
  'inclusionai': 'openrouter',
  'nousresearch': 'openrouter',
  'cognitivecomputations': 'openrouter',
  'arcee-ai': 'openrouter',
  'prime-intellect': 'openrouter',
  'amazon': 'openrouter',
  'baidu': 'openrouter',
  'tencent': 'openrouter',
  'xiaomi': 'openrouter',
  'alibaba': 'openrouter',
  'ibm-granite': 'openrouter',
  // Tilde-prefixed entries are routing variants on models.dev
  '~anthropic': 'openrouter',
  '~google': 'openrouter',
  '~moonshotai': 'openrouter',
  '~openai': 'openrouter',
  // Not yet in our providers
  'perceptron': null,
  'rekaai': null,
  'stepfun': null,
  'upstage': null,
  'writer': null,
  'allenai': null,
  'microsoft': null,
  'essentialai': null,
  'inception': null,
  'liquid': null,
  'nex-agi': null,
  'alfredpros': null,
  'anthracite-org': null,
  'aion-labs': null,
  'deepcogito': null,
  'gryphe': null,
  'inflection': null,
  'kwaipilot': null,
  'mancer': null,
  'morph': null,
  'relace': null,
  'sao10k': null,
  'switchpoint': null,
  'thedrummer': null,
  'undi95': null,
  'ai21': null,
};

module.exports = { PROVIDER_MAP };
